### ISSUE TITLE
`hedera_format_amount` is not safe

### ISSUE THREAD

**Issue by yhql** [LedgerHQ/app-hedera#21]
[hedera_format_amount](https://github.com/LedgerHQ/app-hedera/blob/develop/src/hedera_format.c#L11) crashes (when compiling with `-fsanitize=address`) with the following inputs:

```
hedera_format_amount(-1u, 30);
hedera_format_amount(-1u, 31);
hedera_format_amount(0, 0);
```

The first two produce an out-of-bounds write of 0 past the end of `buf` while the last one reads one byte before `buf`.

As this function is called with parameters coming from externally-controlled parameters transaction description (e.g. [here](https://github.com/LedgerHQ/app-hedera/blob/develop/src/sign_transaction.c#L637-L640) ), it could lead to security problems.

Also, it seems the expected decimal value is parsed as an [`unsigned int`](https://github.com/LedgerHQ/app-hedera/blob/develop/proto/TokenMint.proto#L13) whereas it is cast into an unsigned char when calling `hedera_format_amount` in the portion of code linked above.

**Comment by mehcode** [comment]
> Also, it seems the expected decimal value

Hedera supports setting decimals up to `uint32_t` but the largest _feasible_ decimal amount is probably 16 as the total balance is only a 64-bit number in Hedera. I'm not sure the best idea here, maybe we reject accepting the transaction if a decimal value larger than say 20 is passed?

---

I'll get the safety issues fixed today.
